// <auto-generated />
using System;
using BKM.Utility.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BKM.Utility.Infrastructure.Persistence.Migrations.FileIngestion
{
    [DbContext(typeof(FileIngestionDbContext))]
    partial class FileIngestionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BKM.Utility.Domain.Features.FileIngestion.Entities.IngestedRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RecordType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("RowNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IngestedAt")
                        .HasDatabaseName("IX_IngestedRecords_IngestedAt");

                    b.HasIndex("BatchId", "PayloadHash")
                        .HasDatabaseName("IX_IngestedRecords_BatchId_PayloadHash");

                    b.HasIndex("BatchId", "RowNumber")
                        .HasDatabaseName("IX_IngestedRecords_BatchId_RowNumber");

                    b.HasIndex("FileType", "RecordType")
                        .HasDatabaseName("IX_IngestedRecords_FileType_RecordType");

                    b.ToTable("IngestedRecords", "dbo");
                });

            modelBuilder.Entity("BKM.Utility.Domain.Features.FileIngestion.Entities.IngestionBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DuplicateRows")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long>("ErrorRows")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ParseOptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("SuccessRows")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRows")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_IngestionBatches_StartedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_IngestionBatches_Status");

                    b.ToTable("IngestionBatches", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
